# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

init:
  - git config --global core.autocrlf true

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run test

# Don't actually build.
build: off

